name: app_v1
description: A hybrid Flutter/Kotlin location tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.11
  mongo_dart: ^0.9.0
  crypto: ^3.0.3
  provider: ^6.0.5
  http: ^0.13.6
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/  
